<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('hazard_logs', function (Blueprint $table) {
            $table->id();

            // Human-readable code generated by the edge device / seeder
            // Format: "HAZ-001"  Unique so duplicate detections are rejected.
            $table->string('haz_code', 20)->unique();

            // Hazard classification from the CV model
            $table->enum('type', [
                'Pothole',
                'Road Excavation',
                'Road Barrier',
                'Traffic Sign',
                'Traffic Light',
            ]);

            // Barangay / district label derived from GPS coordinates
            $table->string('area', 100);

            // GPS coordinates of the detected hazard
            $table->decimal('latitude',  10, 7);
            $table->decimal('longitude', 10, 7);

            // CV model confidence score (0.00 – 100.00)
            $table->decimal('confidence', 5, 2)->default(0);

            // Distance in metres from the edge device to the hazard at time of detection
            $table->decimal('distance', 8, 2)->nullable()->default(null);

            // Rider / edge-device identifier.
            // Stored as a code string ("RIDER-001") for now; can be converted to
            // a proper FK once the riders table is in place.
            $table->string('rider_code', 30)->index();

            // Lifecycle state – set to 'resolved' by admin or automated sweep
            $table->enum('status', ['active', 'resolved'])->default('active');

            // When the edge device first detected this hazard (may differ from created_at)
            $table->timestamp('detected_at');

            $table->timestamps(); // created_at = when the record hit the server
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('hazard_logs');
    }
};
